# description: configuration file path, if it's specified as relative path,
# then directory of binary file will be the base directory of configuration file,
# it is recommended to specify absolute path.
# command-line-argument: --config
# type: string
# default: None
config: db_operator.yaml

# description: specify whether db operator runs as daemon mode, if true, db operator will run as a daemon process.
# command-line-argument: --daemon
# type: bool
# default: false
daemon: false

# log configuration
log:
  # description: log file path, if it's specified as relative path,
  # then directory of binary file will be the base directory of log file,
  # it is recommended to specify absolute path.
  # command-line-argument: --log-file
  # type: string
  # default: log/run.log
  file: log/run.log
  # description: log level
  # command-line-argument: --log-level
  # type: string
  # available: [debug, info, warn, error, fatal]
  # default: info
  level: info
  # description: log format
  # command-line-argument: --log-format
  # type: string
  # available: [text, json]
  # default: text
  format: text
  # description: log file max size
  # command-line-argument: --log-max-size
  # unit: MB
  # type: int
  # default: 100
  maxSize: 100
  # description: specify how many days the log file will be kept after rotating,
  # older than max-days files will be removed automatically.
  # command-line-argument: --log-max-days
  # type: int
  # default: 7
  maxDays: 7
  # description: specify how many files will be kept after rotating,
  # the oldest log files will be removed automatically.
  # command-line-argument: --log-max-backups
  # type: int
  # default: 5
  maxBackups: 5
  # description: specify if rotating the log file on starting up
  # command-line-argument: --log-rotate-on-startup
  # type: bool
  # default: false
  rotateOnStartup: false
  # description: specify if logging the message to the stdout as well
  # if no, log message will only be logged to the log file,
  # if yes, log message will be logged to the log file and stdout.
  # command-line-argument: --log-stdout
  # type: bool
  # default: false
  stdout: false

# server configuration
server:
  # description: specify the server listening address, format: host:port
  # command-line-argument: --server-addr
  # type: string
  # default: 0.0.0.0:8510
  addr: "0.0.0.0:8510"
  # description: pid file path, if it's specified as relative path,
  # then directory of binary file will be the base directory of log file,
  # it is recommended to specify absolute path.
  # command-line-argument: --server-pid-file
  # type: string
  # default: db_operator.pid
  pidFile: db_operator.pid
  # description: specify the read timeout of http request, 0 means no timeout
  # command-line-argument: --server-read-timeout
  # unit: second
  # type: int
  # available: 0 - 60
  # default: 5
  readTimeout: 5
  # description: specify the write timeout of http resp, 0 means no timeout
  # command-line-argument: --server-write-timeout
  # unit: second
  # type: int
  # available: 0 - 60
  # default: 10
  writeTimeout: 10
  # description: pprof configuration
  pprof:
    # description: specify if enable the pprof
    # command-line-argument: --server-pprof-enabled
    # type: bool
    # default: false
    enabled: false
  # router configuration
  router:
    # description: specify the alternative base path, this base path will not impact the original api path,
    # but adds additional api paths with specified base path
    # command-line-argument: --server-router-alternative-base-path
    # type: string
    # default: ""
    alternativeBasePath: ""
    # description: specify the real body path of the json body of the http request
    # command-line-argument: --server-router-alternative-body-path
    # type: string
    # default: ""
    alternativeBodyPath: ""
    # description: specify the http return code when the server encountered an error
    # command-line-argument: --server-router-http-error-code
    # type: int
    # available: [200, 500]
    # default: 500
    httpErrorCode: 500

# database configuration
db:
  # database operator configuration
  dbo:
    # mysql configuration
    mysql:
      # description: database address, format: host:port
      # command-line-argument: --db-dbo-mysql-addr
      # type: string
      # default: 127.0.0.1:3306
      addr: "127.0.0.1:3306"
      # description: database name
      # command-line-argument: --db-dbo-mysql-name
      # type: string
      # default: dbo
      name: dbo
      # description: database username
      # command-line-argument: --db-dbo-mysql-user
      # type: string
      # default: root
      user: root
      # description: database password
      # command-line-argument: --db-dbo-mysql-pass
      # type: string
      # default: root
      pass: root
  # connection pool configuration
  pool:
    # description: connection pool could create up to this value of connections
    # command-line-argument: --db-pool-max-connections
    # type: int
    # default: 20
    maxConnections: 20
    # description: connection pool will create {init-connections} connections at the beginning,
    # connection pool could grow up necessarily, up to db-max-connection
    # command-line-argument: --db-pool-init-connections
    # type: int
    # default: 5
    initConnections: 5
    # description: connections more than this value will be released soon to save database resource
    # command-line-argument: --db-pool-max-idle-connections
    # type: int
    # default: 20
    maxIdleConnections: 10
    # description: connection pool will release connections more than {max-idle-connections} every this value of seconds
    # command-line-argument: --db-pool-max-idle-time
    # unit: second
    # type: int
    # default: 1800
    maxIdleTime: 1800
    # description: getting a connection from the pool will wait for {max-wait-time} seconds at most, -1 means wait forever
    # command-line-argument: --db-pool-max-wait-time
    # unit: second
    # type: int
    # default: 1
    maxWaitTime: 1
    # description: getting a connection from the pool will retry {max-retry-count} times at most, -1 means retry forever
    # command-line-argument: --db-pool-max-retry-count
    # type: int
    # default: -1
    maxRetryCount: -1
    # description: connection pool keeps alive of connections in the pool every this value of seconds to avoid database connection timeout
    # command-line-argument: --db-pool-keep-alive-interval
    # unit: second
    # type: int
    # default: 300
    keepAliveInterval: 300

# mysql configuration
mysql:
  # description: specify the default mysql version
  # command-line-argument: --mysql-version
  # type: string
  # default: 8.0.32
  version: 8.0.32
  # description: specify the default mysql version int
  # command-line-argument: --mysql-version-int
  # type: string
  # default: 8032
  versionInt: 8032
  # description: specify the mysql binary installation package directory
  # command-line-argument: --mysql-installation-package-dir
  # type: string
  # default: /data/software/mysql
  installationPackageDir: /data/software/mysql
  # description: specify the mysql binary installation temporary directory
  # command-line-argument: --mysql-installation-temporary-dir
  # type: string
  # default: /data/software/mysql/tmp
  installationTemporaryDir: /data/software/mysql/tmp
  # parameter configuration
  parameter:
    # description: specify the default max connections
    # command-line-argument: --mysql-parameter-max-connections
    # type: int
    # default: 2000
    maxConnections: 2000
    # description: specify the default innodb buffer pool size
    # command-line-argument: --mysql-parameter-innodb-buffer-pool-size
    # unit: MB
    # type: int
    # default: 1024
    innodbBufferPoolSize: 1024
    # description: specify the default innodb io capacity
    # command-line-argument: --mysql-parameter-innodb-io-capacity
    # type: int
    # default: 1000
    innodbIOCapacity: 1000
  # user configuration
  user:
    # description: specify the os user
    # command-line-argument: --mysql-user-os-user
    # type: string
    # default: root
    osUser: root
    # description: specify the os password
    # command-line-argument: --mysql-user-os-pass
    # type: string
    # default: root
    osPass: root
    # description: specify the default default root password
    # command-line-argument: --mysql-user-root-pass
    # type: string
    # default: root
    rootPass: root
    # description: specify the default admin user
    # command-line-argument: --mysql-user-admin-user
    # type: string
    # default: admin
    adminUser: admin
    # description: specify the default admin password
    # command-line-argument: --mysql-user-admin-pass
    # type: string
    # default: admin
    adminPass: admin
    # description: specify the default mysqld-multi user
    # command-line-argument: --mysql-user-mysqld-multi-user
    # type: string
    # default: mysqld_multi
    mysqldMultiUser: mysqld_multi
    # description: specify the default mysqld-multi password
    # command-line-argument: --mysql-user-mysqld-multi-pass
    # type: string
    # default: mysqld_multi
    mysqldMultiPass: mysqld_multi
    # description: specify the default replication user
    # command-line-argument: --mysql-user-replication-user
    # type: string
    # default: replication
    replicationUser: replication
    # description: specify the default replication password
    # command-line-argument: --mysql-user-replication-pass
    # type: string
    # default: replication
    replicationPass: replication
    # description: specify the default monitor user
    # command-line-argument: --mysql-user-monitor-user
    # type: string
    # default: pmm
    monitorUser: pmm
    # description: specify the default monitor password
    # command-line-argument: --mysql-user-monitor-pass
    # type: string
    # default: pmm
    monitorPass: pmm
    # description: specify the default das user
    # command-line-argument: --mysql-user-das-user
    # type: string
    # default: das
    dasUser: das
    # description: specify the default das password
    # command-line-argument: --mysql-user-das-pass
    # type: string
    # default: das
    dasPass: das
  # description: specify the default mysql operation timeout
  # command-line-argument: --mysql-operation-timeout
  # unit: second
  # type: int
  # default: 86400
  operationTimeout: 86400

# pmm configuration
pmm:
  # server configuration
  server:
    # description: specify the default pmm server address
    # command-line-argument: --pmm-server-addr
    # type: string
    # default: 127.0.0.1:443
    addr: 127.0.0.1:443
    # description: specify the default pmm server user
    # command-line-argument: --pmm-server-user
    # type: string
    # default: admin
    user: admin
    # description: specify the default pmm server password
    # command-line-argument: --pmm-server-pass
    # type: string
    # default: admin
    pass: admin
  # client configuration
  client:
    # description: specify the default pmm client version
    # command-line-argument: --pmm-client-version
    # type: string
    # default: 2.34.0
    version: 2.34.0
    # description: specify the pmm client installation package directory
    # command-line-argument: --pmm-client-installation-package-dir
    # type: string
    # default: /data/software/mysql
    installationPackageDir: /data/software/mysql









