package message

import (
	"github.com/romberli/go-util/config"
)

const (
	ErrPrintHelpInfo                           = 400001
	ErrEmptyLogFileName                        = 400002
	ErrNotValidLogFileName                     = 400003
	ErrNotValidLogLevel                        = 400004
	ErrNotValidLogFormat                       = 400005
	ErrNotValidLogMaxSize                      = 400006
	ErrNotValidLogMaxDays                      = 400007
	ErrNotValidLogMaxBackups                   = 400008
	ErrNotValidServerPort                      = 400009
	ErrNotValidPidFile                         = 400010
	ErrValidateConfig                          = 400011
	ErrInitDefaultConfig                       = 400012
	ErrReadConfigFile                          = 400013
	ErrOverrideCommandLineArgs                 = 400014
	ErrAbsoluteLogFilePath                     = 400015
	ErrInitLogger                              = 400016
	ErrRotateLogFile                           = 400017
	ErrBaseDir                                 = 400018
	ErrInitConfig                              = 400019
	ErrCheckServerPid                          = 400020
	ErrCheckServerRunningStatus                = 400021
	ErrServerIsRunning                         = 400022
	ErrStartAsForeground                       = 400023
	ErrSavePidToFile                           = 400024
	ErrKillServerWithPid                       = 400025
	ErrKillServerWithPidFile                   = 400026
	ErrGetPidFromPidFile                       = 400027
	ErrSetSid                                  = 400028
	ErrRemovePidFile                           = 400029
	ErrNotValidDBAddr                          = 400030
	ErrNotValidDBName                          = 400031
	ErrNotValidDBUser                          = 400032
	ErrNotValidDBPass                          = 400033
	ErrNotValidDBPoolMaxConnections            = 400034
	ErrNotValidDBPoolInitConnections           = 400035
	ErrNotValidDBPoolMaxIdleConnections        = 400036
	ErrNotValidDBPoolMaxIdleTime               = 400037
	ErrNotValidDBPoolMaxWaitTime               = 400038
	ErrNotValidDBPoolMaxRetryCount             = 400039
	ErrNotValidDBPoolKeepAliveInterval         = 400040
	ErrInitConnectionPool                      = 400041
	ErrNotValidServerReadTimeout               = 400042
	ErrNotValidServerWriteTimeout              = 400043
	ErrNotValidServerAddr                      = 400044
	ErrNotValidServerRouterAlternativeBasePath = 400045
	ErrNotValidServerRouterHTTPErrorCode       = 400046
	ErrFieldNotExists                          = 400047
	ErrGetRawData                              = 400048
	ErrUnmarshalRawData                        = 400049
	ErrGenerateNewMapWithTag                   = 400050
	ErrMarshalData                             = 400051
	ErrTypeConversion                          = 400052
	ErrFieldNotExistsOrWrongType               = 400053
	ErrNotValidTimeLayout                      = 400054
	ErrNotValidTimeDuration                    = 400055
	ErrGetResponseCode                         = 400056
	ErrSetResponseCode                         = 400057
	ErrGinRecovery                             = 400058
	ErrNotValidFilePath                        = 400059
	ErrOverrideConfigByCLI                     = 400060
	ErrInitDerivedConfig                       = 400061
	ErrSortAddrs                               = 400062
)

func initErrorMessage() {
	Messages[ErrPrintHelpInfo] = config.NewErrMessage(DefaultMessageHeader, ErrPrintHelpInfo, "got message when printing help information")
	Messages[ErrEmptyLogFileName] = config.NewErrMessage(DefaultMessageHeader, ErrEmptyLogFileName, "log file name could not be an empty string")
	Messages[ErrNotValidLogFileName] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogFileName, "log file name must be either unix or windows path format, %s is not valid")
	Messages[ErrNotValidLogLevel] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogLevel, "log level must be one of [debug, info, warn, message, fatal], %s is not valid")
	Messages[ErrNotValidLogFormat] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogFormat, "log format must be either text or json, %s is not valid")
	Messages[ErrNotValidLogMaxSize] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogMaxSize, "log max size must be between %d and %d, %d is not valid")
	Messages[ErrNotValidLogMaxDays] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogMaxDays, "log max days must be between %d and %d, %d is not valid")
	Messages[ErrNotValidLogMaxBackups] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidLogMaxBackups, "log max backups must be between %d and %d, %d is not valid")
	Messages[ErrNotValidServerPort] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidServerPort, "Server port must be between %d and %d, %d is not valid")
	Messages[ErrNotValidPidFile] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidPidFile, "pid file name must be either unix or windows path format, %s is not valid")
	Messages[ErrValidateConfig] = config.NewErrMessage(DefaultMessageHeader, ErrValidateConfig, "validate config failed")
	Messages[ErrInitDefaultConfig] = config.NewErrMessage(DefaultMessageHeader, ErrInitDefaultConfig, "init default configuration failed")
	Messages[ErrReadConfigFile] = config.NewErrMessage(DefaultMessageHeader, ErrReadConfigFile, "read config file failed")
	Messages[ErrOverrideCommandLineArgs] = config.NewErrMessage(DefaultMessageHeader, ErrOverrideCommandLineArgs, "override command line arguments failed")
	Messages[ErrAbsoluteLogFilePath] = config.NewErrMessage(DefaultMessageHeader, ErrAbsoluteLogFilePath, "get absolute path of log file failed. log file: %s")
	Messages[ErrInitLogger] = config.NewErrMessage(DefaultMessageHeader, ErrInitLogger, "initialize logger failed")
	Messages[ErrRotateLogFile] = config.NewErrMessage(DefaultMessageHeader, ErrRotateLogFile, "rotate log file failed")
	Messages[ErrBaseDir] = config.NewErrMessage(DefaultMessageHeader, ErrBaseDir, "get base dir of %s failed")
	Messages[ErrInitConfig] = config.NewErrMessage(DefaultMessageHeader, ErrInitConfig, "init config failed")
	Messages[ErrCheckServerPid] = config.NewErrMessage(DefaultMessageHeader, ErrCheckServerPid, "check server pid file failed")
	Messages[ErrCheckServerRunningStatus] = config.NewErrMessage(DefaultMessageHeader, ErrCheckServerRunningStatus, "check server running status failed")
	Messages[ErrServerIsRunning] = config.NewErrMessage(DefaultMessageHeader, ErrServerIsRunning, "pid file exists or server is still running. pid file: %s")
	Messages[ErrStartAsForeground] = config.NewErrMessage(DefaultMessageHeader, ErrStartAsForeground, "got message when starting das as foreground")
	Messages[ErrSavePidToFile] = config.NewErrMessage(DefaultMessageHeader, ErrSavePidToFile, "got message when writing pid to file")
	Messages[ErrKillServerWithPid] = config.NewErrMessage(DefaultMessageHeader, ErrKillServerWithPid, "kill server failed. pid: %d")
	Messages[ErrKillServerWithPidFile] = config.NewErrMessage(DefaultMessageHeader, ErrKillServerWithPidFile, "kill server with pid file failed. pid: %d, pid file: %s")
	Messages[ErrGetPidFromPidFile] = config.NewErrMessage(DefaultMessageHeader, ErrGetPidFromPidFile, "get pid from pid file failed. pid file: %s")
	Messages[ErrSetSid] = config.NewErrMessage(DefaultMessageHeader, ErrSetSid, "set sid failed when daemonizing server")
	Messages[ErrRemovePidFile] = config.NewErrMessage(DefaultMessageHeader, ErrRemovePidFile, "remove pid file failed. pid file: %s")
	Messages[ErrNotValidDBAddr] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBAddr, "database address must be formatted as host:port, %s is not valid")
	Messages[ErrNotValidDBName] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBName, "database name must be a string, %s is not valid")
	Messages[ErrNotValidDBUser] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBUser, "database user name must be a string, %s is not valid")
	Messages[ErrNotValidDBPass] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPass, "database password must be a string, %s is not valid")
	Messages[ErrNotValidDBPoolMaxConnections] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolMaxConnections, "database max connections must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolInitConnections] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolInitConnections, "database initial connections must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolMaxIdleConnections] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolMaxIdleConnections, "database max idle connections must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolMaxIdleTime] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolMaxIdleTime, "database max idle time must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolMaxWaitTime] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolMaxWaitTime, "database max wait time must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolMaxRetryCount] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolMaxRetryCount, "database max retry count must be between %d and %d, %d is not valid")
	Messages[ErrNotValidDBPoolKeepAliveInterval] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidDBPoolKeepAliveInterval, "database keep alive interval must be between %d and %d, %d is not valid")
	Messages[ErrInitConnectionPool] = config.NewErrMessage(DefaultMessageHeader, ErrInitConnectionPool, "init connection pool failed.")
	Messages[ErrNotValidServerReadTimeout] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidServerReadTimeout, "server read timeout must be between %d and %d, %d is not valid")
	Messages[ErrNotValidServerWriteTimeout] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidServerWriteTimeout, "server write timeout must be between %d and %d, %d is not valid")
	Messages[ErrNotValidServerAddr] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidServerAddr, "server addr must be formatted as host:port, %s is not valid")
	Messages[ErrFieldNotExists] = config.NewErrMessage(DefaultMessageHeader, ErrFieldNotExists, "field does not exist. field name: %s")
	Messages[ErrGetRawData] = config.NewErrMessage(DefaultMessageHeader, ErrGetRawData, "get raw data from http body failed")
	Messages[ErrUnmarshalRawData] = config.NewErrMessage(DefaultMessageHeader, ErrUnmarshalRawData, "unmarshal raw data failed")
	Messages[ErrGenerateNewMapWithTag] = config.NewErrMessage(DefaultMessageHeader, ErrGenerateNewMapWithTag, "generate new map with tag %s failed")
	Messages[ErrMarshalData] = config.NewErrMessage(DefaultMessageHeader, ErrMarshalData, "marshal service failed")
	Messages[ErrTypeConversion] = config.NewErrMessage(DefaultMessageHeader, ErrTypeConversion, "type conversion failed")
	Messages[ErrFieldNotExistsOrWrongType] = config.NewErrMessage(DefaultMessageHeader, ErrFieldNotExistsOrWrongType, "filed does not exist or is wrong type. field name: %s")
	Messages[ErrNotValidTimeLayout] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidTimeLayout, "time layout must be formatted as yyyy-MM-dd HH:mm:ss, %s is not valid")
	Messages[ErrNotValidTimeDuration] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidTimeDuration, "time duration must be formatted, e.g. such as 300ms, -1.5h or 2h45m, %s is not valid")
	Messages[ErrGinRecovery] = config.NewErrMessage(DefaultMessageHeader, ErrGinRecovery, "gin Recovery: panic recovered")
	Messages[ErrNotValidFilePath] = config.NewErrMessage(DefaultMessageHeader, ErrNotValidFilePath, "file path must be either unix or windows path, %s is not valid")
	Messages[ErrOverrideConfigByCLI] = config.NewErrMessage(DefaultMessageHeader, ErrOverrideConfigByCLI, "override config by command line interface failed")
	Messages[ErrInitDerivedConfig] = config.NewErrMessage(DefaultMessageHeader, ErrInitDerivedConfig, "init derived config failed")
	Messages[ErrSortAddrs] = config.NewErrMessage(DefaultMessageHeader, ErrSortAddrs, "sort addrs failed. addrs: %v")
}
